# specify the base image for web
FROM moneroboxdev/docker-compose:1.24.0

# Create app directory
WORKDIR /usr/src/app

# checkout git repo 
RUN git clone https://github.com/Jasonhcwong/RPi-Monitor-Monerobox.git && cd RPi-Monitor-Monerobox && git checkout btc_ltc

# Copy executable file
RUN mv /usr/src/app/RPi-Monitor-Monerobox/src/usr/bin/* /usr/src/app/

# Copy web files
RUN mv /usr/src/app/RPi-Monitor-Monerobox/src/usr/share/rpimonitor/web /usr/src/app/

# Copy config files
RUN mv /usr/src/app/RPi-Monitor-Monerobox/src/etc /usr/src/app/

# Create folder for datastore and log
RUN mkdir -p /usr/src/app/data
RUN mkdir -p /usr/src/app/log

# remove git repo
RUN rm -rf /usr/src/app/RPi-Monitor-Monerobox

ENTRYPOINT ["/usr/src/app/rpimonitord", "-c", "/usr/src/app/etc/rpimonitor/daemon.conf",  "-c", "/usr/src/app/etc/rpimonitor/template/system.conf"]

