version: '2.4'

services:
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    restart: on-failure
    image: moneroboxdev/bitcoind:latest
    mem_limit: 1000m
    memswap_limit: 1500m
    cpus: 3
    cpuset: "1-3"
    volumes:
      - data_bitcoin:/data/bitcoin
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.30
    ports:
      - "8333:8333"

  lnd_btc:
    container_name: lnd_btc
    hostname: lnd_btc
    restart: on-failure
    image: moneroboxdev/lnd:latest
    mem_limit: 500m
    memswap_limit: 700m
    oom_kill_disable: true
    cpus: 3
    cpuset: "1-3"
    volumes:
      - data_lnd_btc:/data/lnd_btc
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.31
    ports:
      - "9735:9735"
      - "10008:8080"
      - "10009:10009"
    entrypoint: /usr/src/app/lnd_entrypoint.sh bitcoin
    depends_on:
      - bitcoind

  rtl_btc:
    container_name: rtl_btc
    hostname: rtl_btc
    restart: on-failure
    image: moneroboxdev/rtl:latest
    mem_limit: 128m
    memswap_limit: 256m
    oom_kill_disable: true
    cpus: 3
    cpuset: "1-3"
    volumes:
      - data_lnd_btc:/data/lnd_btc
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.32
    ports:
      - "3000:3000"
    depends_on:
      - bitcoind
      - lnd_btc
    environment:
      - RTL_CONFIG_PATH=/settings/rtl_btc/RTL.conf

networks:
  monerobox:
    external: true

volumes:
  data_bitcoin:
    external: true
  data_lnd_btc:
    external: true
  settings:
    external: true

