version: '2.4'

services:
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    restart: on-failure
    image: monerobox/bitcoind:latest
    cpus: 3
    cpuset: "1-3"
    volumes:
      - data_bitcoin:/data/bitcoin
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.30

networks:
  monerobox:
    external: true

volumes:
  data_bitcoin:
    external: true
  settings:
    external: true

