version: '2.4'

services:
  manager:
    container_name: manager
    hostname: manager
    restart: on-failure
    image: moneroboxdev/manager:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    environment:
      - HOST_HOSTNAME
      - HOST_IP
    volumes:
      - /run/docker.sock:/run/docker.sock
      - /usr//bin/docker:/usr/bin/docker
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.2

  tor:
    container_name: tor
    hostname: tor
    restart: always
    image: moneroboxdev/tor:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    volumes:
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.3

  web:
    container_name: web
    hostname: web
    restart: always
    image: moneroboxdev/web:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    volumes:
      - /sys/class/net/eth0:/usr/src/app/host_dev/net/eth0
      - /run/systemd:/run/systemd
      - /run/docker.sock:/run/docker.sock
      - /usr//bin/docker:/usr/bin/docker
      - settings:/settings
      - data_monero:/data/monero
    environment:
      - HOST_HOSTNAME
      - HOST_IP
    ports:
      - "80:80"
    networks:
      monerobox:
        ipv4_address: 172.20.1.4

  stunnel:
    container_name: stunnel
    hostname: stunnel
    restart: always
    image: moneroboxdev/stunnel:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    volumes:
      - settings:/settings
    ports:
      - "8080:8080"
    networks:
      monerobox:
        ipv4_address: 172.20.1.5

volumes:
  settings:
    external: true
  data_monero:
    external: true

networks:
  monerobox:
    external: true
